### ISSUE TITLE
OSError: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by daluisgarcia** [FirebirdSQL/fdb#116]
Hello, I am developing an app in python 3.10.8 (due to other package limitation) and I am getting this error. Using the version 2.0.0 of this package. Working on Windows

The error raised by the package is the following:
```
Traceback (most recent call last):
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\main.py", line 22, in <module>
    interface()
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\main.py", line 12, in interface
    window = MainWindow()
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\main_window.py", line 54, in __init__
    con = Connection(self.config['valery'])
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\valery_connection.py", line 7, in __init__
    self.conn = firebirdsql.connect(
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\venv\lib\site-packages\fdb\fbcore.py", line 803, in connect
    load_api(fb_library_name)
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\venv\lib\site-packages\fdb\fbcore.py", line 231, in load_api
    setattr(sys.modules[__name__], 'api', ibase.fbclient_API(fb_library_name))
  File "C:\Users\Daniel Luis\Projects\arotech\valery-purchase-invoice-by-excel\venv\lib\site-packages\fdb\ibase.py", line 1396, in __init__
    fb_library = WinDLL(fb_library_name)
  File "C:\Users\Daniel Luis\.pyenv\pyenv-win\versions\3.10.9\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by pcisar** [comment]
It seems that you are trying to access 64-bit version of Firebird from 32-bit application. It's possible, but you need to use 32-bit Firebird client libary (fbclient.dll).
