### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by thijsvandien** [FirebirdSQL/fdb#117]
Currently `fdb` won't work using the just released version of Python:

```
>>> import fdb
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    import fdb
  File "/Users/tvdien/.pyenv/versions/3.13.0/lib/python3.13/site-packages/fdb/__init__.py", line 28, in <module>
    from fdb import gstat
  File "/Users/tvdien/.pyenv/versions/3.13.0/lib/python3.13/site-packages/fdb/gstat.py", line 28, in <module>
    from locale import LC_ALL, LC_CTYPE, getlocale, setlocale, resetlocale
ImportError: cannot import name 'resetlocale' from 'locale' (/Users/tvdien/.pyenv/versions/3.13.0/lib/python3.13/locale.py). Did you mean: 'setlocale'?
```

**Comment by cdr60** [comment]
Same trouble
As It's high blocking bug for me, I've temporary fixed it by removing resetlocale from : (I know it's bad !)
#from locale import LC_ALL, LC_CTYPE, getlocale, setlocale, resetlocale
and replacing resetlocale(_LOCALE_) by setlocale(_LOCALE_, '')
and be sure to set my locale (fr_FR, UTF-8 for me) then locale[0] will not be None

**Comment by bkcsfi** [comment]
Can someone please update the release version on pypi so this fix becomes available via pip et all?

Last release on pypi appears to be 2.0.2

**Comment by thijsvandien** [comment]
@pcisar Another request here for a release for this to take effect.
